language: node_js

cache:
  directories:
    - node_modules
  
notifications:
  email: false

services:
  - mongodb

node_js:
  - "8"
before_script:
  - npm prune
  - mongo test --eval 'db.createUser({user:"admin",pwd:"admin",roles:["readWrite"]});'
  - npm run build

script:
  - npm run test:coverage
  - npm run lint

after_success:
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
