language: node_js
node_js:
  - "8"
script: 
  - npm run test:coverage
  - npm run lint
cache:
  directories:
    - node_modules
branches:
  only: 
    - master

services:
  - mongodb

before_script:
  - mongo test --eval 'db.createUser({user:"admin",pwd:"admin",roles:["readWrite"]});'
