sudo: false

language: node_js

cache:
  directories:
    - node_modules

services:
  - mongodb

node_js:
  - "8"

before_script:
  - npm run build
  
notifications:
  disabled: true

install:
  - npm install -g codecov
  - npm install

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
    
script:
  - npm test
  - codecov
